### ISSUE TITLE
CDN JS-lib Inclusion?

### ISSUE THREAD

**Issue by joemccann** [christianalfoni/react-app-boilerplate#5]
Not technically an issue or bug, but am curious as to how I can include a CDN-hosted version of jQuery (or anything for that matter) in the gulp file to include in the `<head>` the CDN-hosted version of jQuery when I run the `deploy` gulp configuration?

This is a rock solid boilerplate, btw.

**Comment by christianalfoni** [comment]
Hi @joemccann!

That is a good question! I searched around a bit and found this one:

https://www.npmjs.com/package/browserify-global-shim

I suppose you could just use that configuration when creating your distributed build. And in your html file just insert jquery CDN at the top manually or using some other build process :-)

did that answer the question?

thanks for the feedback btw!

**Comment by joemccann** [comment]
yes it does.  I just added it to the `index.html` in the `dist` directory
and all is well. Just wondered if there was a cleaner step than manually
adding it.

**Comment by christianalfoni** [comment]
I often use the FS module, writeFile, readFile etc. to create custom HTML. Like:

```html
<html>
  <head>
    {{CDN_SCRIPTS}}
  </head>
<body>

</body>
```
Then I read the file, just use replace to update the placeholders, and then write it again. So I would suggest coding something like that into the workflow. Hope that made sense :-)

**Comment by joemccann** [comment]
yup nice one thanks

**Comment by christianalfoni** [comment]
Cool! good luck :-)
