### ISSUE TITLE
JSX Gulp

### ISSUE THREAD

**Issue by Serfenia** [christianalfoni/react-app-boilerplate#6]
Hello,

I cloned your repo and installed all dependencies using 'npm install'.

Right after I tried to run the gulp command but getting errors on the JSX syntax? 

Parsing file path/tol/Boilerplate/app/App.js: Unexpected token (7:3)

Regards,
Patrick

**Comment by christianalfoni** [comment]
Hi there @Serfenia ,

That sounds really weird. It works fine when I run it locally. Have gotten other issues too, but not related to being able to run it at all. Hm, that is strange.

You running on windows? Maybe you should try using `sudo npm install`?

**Comment by Serfenia** [comment]
Hey @christianalfoni 

Haha no not working on Windows. I just did a sudo install. Still getting the same error, seems that the reactify doesn't do it's work properly?

The Vendors are built btw.

**Comment by christianalfoni** [comment]
Hehe, got to ask ;-) What version of Node are you running?

tir. 10. mar. 2015 kl. 09.16 skrev Patrick van Vuuren <
notifications@github.com>:

**Comment by Serfenia** [comment]
I just updated the version of Node. Appeared to be an older version. It works now, thanks!

**Comment by christianalfoni** [comment]
Great! :+1:
